### ISSUE TITLE
サーバーサイドのSpot情報格納

### ISSUE THREAD

**Issue by thtitech** [thtitech/UBNClientApplication#12]
## 内容
デモに必要なSpotの情報を格納する
デモ時にはUsecaseを2つ行う
Usecase 1: デート
Usecase 2: 大人数

その際に他の選択肢も3, 4個提示できるようにしている

**Comment by CometHelp** [comment]
コースは適宜変更してください。

@ktakahiro 
case1 浅草でデート
浅草->谷根千->ご飯->スカイツリー
@CometHelp
case2 横浜大人数
カップヌードルミュージアム->中華街->山下公園

**Comment by CometHelp** [comment]
クロールするならここからにしたい
https://iko-yo.net/facilities/
