### ISSUE TITLE
プルダウンの作成

### ISSUE THREAD

**Issue by thtitech** [thtitech/UBNClientApplication#13]
## プルダウンの作成
2画面 (MainSpotの選択画面) と 3画面 (SubSpotの選択画面) においてプルダウンを作成し，各Spotの詳細を表示できるようにする

## 期限
11/13の動画撮影前
無理そうならSlackで相談

**Comment by thtitech** [comment]
たぶんだけど，表示されているTextViewをクリックしたイベントを受け取って (http://sandragon.hatenablog.com/entry/2013/07/09/014639)  それに連動させて下にTextViewを表示するのが良さそう

**Comment by mikecat** [comment]
`ExpandableListView`じゃだめなのん？

**Comment by thtitech** [comment]
ごめん， `ExpandableListView` がよくわかってなかったけど，プルダウン作成できるならそれで構いません

**Comment by mikecat** [comment]
できたっぽい
e7313d08c8bbc96867c4cc0fdc68c385fbda5445
