### ISSUE TITLE
動作の確認

### ISSUE THREAD

**Issue by thtitech** [thtitech/UBNClientApplication#15]
## 内容
1画面目から4画面目までをすべて正しく動作することの検証．APIキーの都合上，長田くんのPCでしか実行できないので，僕と日程をすりあわせて確認します．

## 日程
Slack上で話し合う

**Comment by mikecat** [comment]
Google
https://developers.google.com/maps/documentation/android-api/?hl=ja
でキーとって`app/src/main/res/values/api_key.xml`に置けば動かせるはずだけど、取りたくない？
書き方は同`values`ディレクトリの`.gitignore`に書いてある。
